name: Multiple Env Stages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      URL: ${{ vars.MSG }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo ${{ vars.MSG }}

  QA:
    runs-on: ubuntu-latest
    environment: QA
    env:
      URL: ${{ vars.MSG }}
    needs: DEV

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo ${{ vars.MSG }}

  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      URL: ${{ vars.MSG }}
    needs: QA

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo ${{ vars.MSG }}
