name: Multiple Env Stages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo This is Dev!

  QA:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo This is QA!

  Staging:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo This is Staging!
